---
- name: Include vars
  include_vars: ../vars/main.yml

- name: Ensure EPEL is enabled
  yum:
    name: epel-release
    state: present
  become: True

- name: Ensure nginx is present
  yum:
    name: nginx
    state: present
  become: True

- name: Ensure nginx is running
  service:
    name: nginx
    state: started
    enabled: True
  become: True

- name: Ensure HTTP can pass the firewall
  firewalld:
    service: http
    state: enabled
    permanent: True
    immediate: True
  become: True

- name: Ensure HTTPS can pass the firewall
  firewalld:
    service: https
    state: enabled
    permanent: True
    immediate: True
  become: True

- name: Setup selinux for alternate HTTP port
  seport:
    ports: 80
    proto: tcp
    setype: http_port_t
    state: present

- name: Setup selinux for alternate HTTPS port
  seport:
    ports: 443
    proto: tcp
    setype: http_port_t
    state: present

- name: Copy nginx.conf
  template:
    src: nginx.conf
    dest:  /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  become: True

- name: Copy conf.d/default.conf
  template:
    src: default.conf
    dest:  /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: 0644
  become: True

- name: Copy conf.d/default_ssl.conf
  template:
    src: default_ssl.conf
    dest:  /etc/nginx/conf.d/default_ssl.conf
    owner: root
    group: root
    mode: 0644
  become: True

- name: Copy conf.d/edusrv56a.t-2.com.conf
  template:
    src: edusrv56a.t-2.com.conf
    dest:  /etc/nginx/conf.d/edusrv56a.t-2.com.conf
    owner: root
    group: root
    mode: 0644
  become: True

- name: Copy conf.d/edusrv56a.t-2.com_ssl.conf
  template:
    src: edusrv56a.t-2.com_ssl.conf
    dest:  /etc/nginx/conf.d/edusrv56a.t-2.com_ssl.conf
    owner: root
    group: root
    mode: 0644
  become: True

- name: Copy conf.d/edusrv56b.t-2.com.conf
  template:
    src: edusrv56b.t-2.com.conf
    dest:  /etc/nginx/conf.d/edusrv56b.t-2.com.conf
    owner: root
    group: root
    mode: 0644
  become: True

- name: Copy conf.d/edusrv56b.t-2.com_ssl.conf
  template:
    src: edusrv56b.t-2.com_ssl.conf
    dest:  /etc/nginx/conf.d/edusrv56b.t-2.com_ssl.conf
    owner: root
    group: root
    mode: 0644
  become: True
  notify: restart nginx

- name: Ensure services are restarted
  meta: flush_handlers
