- name: Setup firewalld for 4738/tcp SSH port
  firewalld:
    zone: public
    port: 4738/tcp
    permanent: yes
    immediate: yes
    state: enabled

- name: Setup selinux for alternate SSH port
  seport:
    ports: 4738
    proto: tcp
    setype: ssh_port_t
    state: present

- name: Setup alternate SSH port
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^#Port"
    line: "Port 4738"
  notify: "restart sshd"

# We notified "Restart sshd" if we modified the sshd config.
# By calling flush_handlers, we make sure the handler is run *right now*
- name: Ensure SSH is reloaded if need be
  meta: flush_handlers
