---
- name: Include vars
  include_vars: ../vars/main.yml

- name: Ensure EPEL is enabled
  yum:
    name: epel-release
    state: present
  become: True

- name: Ensure php modules are present
  yum:
    name:
      - php-mysqlnd
      - php-dom
      - php-simplexml
      - php-xml
      - php-xmlreader
      - php-curl
      - php-exif
      - php-ftp
      - php-gd
      - php-iconv
      - php-json
      - php-mbstring
      - php-posix
      - php-sockets
      - php-tokenizer
    state: present
  become: True

- name: Ensure services are restarted
  meta: flush_handlers
