---
- name: Include vars
  include_vars: ../vars/main.yml

- name: Ensure EPEL is enabled
  yum:
    name: epel-release
    state: present
  become: True

- name: Install yum utils
  yum:
    name: yum-utils
    state: latest
  become: True

- name: Install device-mapper-persistent-data
  yum:
    name: device-mapper-persistent-data
    state: latest
  become: True

- name: Install lvm2
  yum:
    name: lvm2
    state: latest
  become: True

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  become: True

- name: Install Docker
  package:
    name: docker-ce
    state: latest
  become: True

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: True

- name: Ensure services are restarted
  meta: flush_handlers
