---
- name: Ensure ansible user exists
  user:
    name: ansible
    state: present
    comment: Ansible
- name: Ensure ansible user accepts the SSH key
  authorized_key:
    user: ansible
    key: https://raw.githubusercontent.com/jstopinsek/ansible-git/main/roles/common/files/ansible.key
    state: present
- name: Ensure the ansible user is sudoer with no password required
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^ansible ALL\='
    line: 'ansible ALL=(ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'
