- name: do not permit traffic in default zone for ssh service
  firewalld:
    zone: public
    service: ssh
    permanent: yes
    immediate: yes
    state: disabled

- name: Setup selinux remove SSH port 22
  seport:
    ports: 22
    proto: tcp
    setype: ssh_port_t
    state: absent
